ynput/ayon-ftrack

ftrack_common/event_handlers/ftrack_action_handler.py

Event server status action is not case sensitive for role names of user.
1. Change role name of `pypeclub` to e.g. `PyPeCLuB` in ftrack
2. Run event server
3. Status action should be visible in actions list

Ftrack: Role names are not case sensitive in ftrack event server status action

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py

Sync sometimes crashes becase could not query ftrack project by name. This PR is not fixing the issue, just adds option to get more information why the issue happens by logging event data when issue happens.

Sync to AYON logs not found project on ftrack

---

client/ayon_ftrack/tray/ftrack_tray.py
client/ayon_ftrack/tray/user_server.py

Run event server in tray with `--headless` flag so it won't show login UI when server is not available or credentials get invalid.

Run user event server with headless argument

---

client/ayon_ftrack/plugins/publish/collect_webpublisher_credentials.py

User should not be filled with ftrack username during webpublisher. Webpublisher should fill the user based on AYON username instead.

Do not use ftrack user in webpublisher

---

client/ayon_ftrack/event_handlers_to_convert/action_prepare_project.py
client/ayon_ftrack/event_handlers_user/action_batch_task_creation.py
client/ayon_ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
client/ayon_ftrack/event_handlers_user/action_client_review_sort.py
client/ayon_ftrack/event_handlers_user/action_component_open.py
client/ayon_ftrack/event_handlers_user/action_create_cust_attrs.py
client/ayon_ftrack/event_handlers_user/action_create_folders.py
client/ayon_ftrack/event_handlers_user/action_create_project_structure.py
client/ayon_ftrack/event_handlers_user/action_job_killer.py
client/ayon_ftrack/event_handlers_user/action_multiple_notes.py
client/ayon_ftrack/event_handlers_user/action_thumbnail_to_childern.py
client/ayon_ftrack/event_handlers_user/action_thumbnail_to_parent.py
client/ayon_ftrack/event_handlers_user/action_where_run_ask.py
services/processor/processor/default_handlers/action_clone_review_session.py
services/processor/processor/default_handlers/action_multiple_notes.py
services/processor/processor/default_handlers/action_prepare_project.py
services/processor/processor/default_handlers/action_private_project_detection.py
services/processor/processor/default_handlers/action_push_frame_values_to_task.py
services/processor/processor/default_handlers/action_sync_from_ftrack.py
services/processor/processor/default_handlers/action_tranfer_hierarchical_values.py
services/processor/processor/default_handlers/event_first_version_status.py
services/processor/processor/default_handlers/event_next_task_update.py
services/processor/processor/default_handlers/event_push_frame_values_to_task.py
services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/default_handlers/event_task_to_parent_status.py
services/processor/processor/default_handlers/event_task_to_version_status.py
services/processor/processor/default_handlers/event_thumbnail_updates.py
services/processor/processor/default_handlers/event_version_to_task_statuses.py
services/processor/processor/handlers_to_convert/action_create_review_session.py

Ftrack event handlers are ignoring events from projects that are not available in AYON. Also action topics are not clashing with openpype actions. Some of the actions have AYON label in them so they can be recognized when used with OpenPype.

Event handlers work only on AYON projects

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Duplicate of https://github.com/ynput/OpenPype/pull/5939 . With small formatting changes.
The creation of Ftrack components needs to allow for multiple thumbnails. This is important in situations where there could be several reviewable streams, like in the case of a nuke intermediate files preset. Customers have asked for unique thumbnails for each data stream.
For instance, one stream might contain a baked LUT file along with Display and View. Another stream might only include the baked Display and View. These variations can change the overall look. Thus, we found it necessary to depict these differences via thumbnails.

Support integration of multiple thumbnails

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

The variable names `keep_first_subset_name_for_review` have been updated to `keep_first_product_name_for_review` in order to accurately reflect their purpose. This change ensures that the extended asset name is correctly added when necessary and that the extended asset name is reset if not needed.

fix: Update variable names for keeping first product name

---

client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Prepare entity path in using queue, instead of using `"link"` on entity.
Key `"link"` is set to `NOT_SET` when the entity was just created (obviously), so it probably never worked.

Fix extract hierarchy with entity paths

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Multiple reviewable assetVersion components with better grouping to asset version name.
- Add a condition to also check if multiple_reviewable is True before updating the asset name.
1. very difficult to test but basically you need multiple reviewable representations marked as `ftrackreview`.
Source [PR](https://github.com/ynput/OpenPype/pull/6077)

Ftrack: update asset names for multiple reviewable items

---

server/settings/desktopapp_handlers.py
server/settings/service_handlers.py
services/processor/processor/default_handlers/action_delete_entities.py

Moved Delete Folders/Products to service event handlers so user don't have to have runnin ayon launcher to run it.
With that were also moved settings,
I could not find a reason why the action should be local and not service. Could anyone think of a reason?

Delete action is service action

---

client/ayon_ftrack/common/__init__.py
client/ayon_ftrack/common/lib.py
client/ayon_ftrack/common/utils.py
client/ayon_ftrack/event_handlers_user/action_applications.py
client/ayon_ftrack/launch_hooks/post_ftrack_changes.py

Enhanced ftrack prelaunch hook to change status on application launch. The most important change is how parent of ftrack task is found which fixes the hook core logic. Some refactors were made. We're checking if ftrack is enabled for a project before we do any logic.
EDITED:
It was discovered that ftrack application launch logic did not use folder path which caused a lot of troubles, like not changing the status. That was fixed in this PR too.
1. Upload addon to AYON server OR point path in dev bundle to `client` directory
2. Start ayon launcher
3. Launch an application
4. That should trigger change of status (by default should change status to In Progress)

Prelaunch hook: Find ftrack entity

---

client/ayon_ftrack/common/lib.py
server/settings/main.py

Change name of `ftrack_enabled` to `enabled` to move the checkbox to header of ftrack settings.

Change look of enabled checkbox in settings UI

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py

Use `'shortName'` instead of `'short_name'` for new task types in project.

Use correct key for new task types

---

server/settings/main.py

Tweak grammar, plus replace ' -> ` to avoid markdown formatting to make bold words
Formatting didn't look so well up on the site:
E.g. '__any__' should be `__any__`
**Note: Only thing that I feel is still lacking in the description is the order of strength, Is first match first served? (Which seems like it's not because default top entry starts with `__any__` so I guess it'd always be the case?)**

Tweak Settings docstring for PostLaunchHookSettings

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Skip non-image representations when preparing component metadata.
Resolves https://github.com/ynput/ayon-ftrack/issues/66

Skip non image representations for ffprobe

---

client/ayon_ftrack/launch_hooks/post_ftrack_changes.py

Settings of status mapping when application is launched is not case sensisitive.
Status in `ayon+settings://ftrack/post_launch_hook` does not have to be lower cased to make work status change on launch.
Match functionality from PR https://github.com/ynput/OpenPype/pull/6195

Status update on application launch is not case sensitive

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_status.py
server/__init__.py
server/settings/publish_plugins.py

Use product name and type instead of subset and family in settings.
Added conversion of overrides because of possible issues with settings conversions from older versions.

Use new naming in settings

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_status.py
server/settings/publish_plugins.py

Integrate ftrack farm status is using wrong settings keys for current implementation of the plugin. Added correct keys in default settings and added more conversions to handle all the cases.

Fix Integrate ftrack farm status settings

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Fill AYON id on integrated AssetVersion on ftrack.
This PR is related only to client code.
1. Use dev bundle or create package and make sure code from this branch is used.
2. Enable frack addon...
3. Launch host of your choice.
4. Create and publish something that will integrated to ftrack (based on settings of Collect Ftrack Family).
5. After integration go to ftrack, show details of integrated version and it should have filled AYON id with version id in AYON.
6. To make sure it is version id (and not folder id) call this in Tray > Admin > Console
```python
import ayon_api
project_name = "<your project>"
version_id = "<id value from AssetVersion on ftrack>"
print(ayon_api.get_version_by_id(project_name, version_id))
"""
Should print entity data, not `None`.

Add AYON version id to integrated AssetVersion

---

services/processor/processor/default_handlers/action_prepare_project.py

Data of custom attribute definition were not converted from json string to data so prepare project action did crash in the middle of work.
1. Create package from the package
2. Run both leecher and processor using service tools (`./service_tools/start.ps1 services`)
3. Run prepare project action on new project
4. It should finish fine

PrepareProject: Fix custom attribute list values

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Integretate thumbnail if there are not reviewables.
1. Make an instance that does not create reviewable (e.g. model in traypublisher) and add a thumbnail to the instance.
2. Publish. The instance must have assigned ftrack family (based on collect ftrack family).
3. The thumbnail should be on ftrack.

Integrate thumbnail if there are not reviewables

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Make filtering of review representations earlier.
First filter review representation that does not have existing path. Secondly filter image reviewables if there are any movie reviewables before `multiple_reviewable` is assigned.

Integrate ftrack: Filter reviewables before component list loop

---

client/ayon_ftrack/event_handlers_user/action_create_cust_attrs.py

Fixe creation of ftrack custom attributes.
It looks like ftrack changed requirements for creation of custom attributes and `"config"` must be always filled. This issue also discovered that the error was not handled and shown/reported to user at all, so reporting from the action was enhanced.
1. Remove some custom attributes from ftrack if all are already created (should be attribute without config, e.g. boolean).
2. Run Create/Update custom attributes action.
3. The attribute should be created.

Create/Update custom attributes: Can create attributes

---

README.md
server/__init__.py
service_tools/.gitignore
service_tools/main.py
services/processor/processor/download_utils.py
services/processor/processor/server.py

Ftrack processor is able to download service event handlers from other addons.
Ftrack addon allows an addon to define it's custom service handlers by implementing `get_custom_ftrack_handlers_endpoint` returning endpoint leading to file on AYON server.
Processor will use always current production, staging or dev bundle addons (based on used variant in service).
The files are by default stored to appdirs, download root can be changed by env variable. But it will always generate random process id under which are stored the files so it is possible to run multiple processes (or re-use the same docker image). Implemented basic cleanup strategy to remove 1 hour inactive folders.

Processor: Download event handlers from addons

---

client/ayon_ftrack/event_handlers_user/action_applications.py
package.py

Use `get_app_icon_url` from applications addon to show icons instead of using ayon-core icons.
1. Create bundle with this PR and applications addon 0.2.4.
2. Run tray.
3. Discover ftrack actions on ftrack.
4. Application icons shows show correctly.

Applications action: Use applications icon url

---

server/settings/custom_attributes.py

For some reason there is defined attribute name `read_roles` instead of `read_security_roles` so any settings for read roles are not propagated during Create/Update custom attributes.

Settings: Fix attribute name of default read roles attribute

---

server/settings/custom_attributes.py

Change write permissions of AYON id and AYON path to be empty -> any user can change them.
The attributes are filled during publishing on version entity, but if users don't have permissions it just silently logs error without doing it.
This opens possible hell by giving artist permissions to change backend attribute. Maybe we should find better approach how to achieve this in future? Not sure how exactly, maybe by using event system?
Testing requires to have artist user on ftrack without admin permissions.
1. Run tray as admin.
2. Run Create/Update custom attributes action on ftrack to update attributes permissions.
3. Run tray with ftrack user that does not have admin nor API permissions.
4. Publish something.
5. AYON id and AYON path should be filled and Publisher should not show errors …

Attribute permissions: Allow to change AYON ID and path to anyone

---

services/processor/processor/ftrack_session.py
services/processor/processor/server.py

Run cleanup process functionality on crash. Which is potential fix of stuck processor event.
It was reported multiple times that events are not actually processed, but service in web ui is shows as "running". Only service restart helps to resolve the issue. Changes here makes sure that cleanup of process happens when process crashes, not just when is terminated. Hopefully will resolve the issue.
Cleanup process funcationlity stops running threading timers. They can cause that the process is stuck.
I couldn't replicate the issue so I don't know how to test. For now:
1. Start services.
2. They should work as before.

Service processor: Cleanup process on fail

---

server/settings/service_handlers.py

Fix attribute name in settings model.
Status to version settings model has correct attribute name `asset_types_filter` instead of `asset_types_to_skip`.
1. Task to version status propagation works.

Event handlers: Status task to version settings

---

server/__init__.py
server/settings/__init__.py
server/settings/conversions.py
server/settings/service_handlers.py
services/processor/processor/default_handlers/event_next_task_update.py
services/processor/processor/default_handlers/event_task_to_version_status.py
services/processor/processor/default_handlers/event_version_to_task_statuses.py

Added option to set Allow/Deny list of Asset types for "task to version status" and "version to task status" event handlers.
Enhance asset types filtering for the event handlers by allowing to change the filter type. Right now it can be only allow type for task to version and deny type for version to task which might be limiting.
1. Conversion of settings from previous versions should work (during copy settings).
2. Filtering set in settings works and statuses are changed accordingly.

Status propagation: Better asset types filtering

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py

Added sync of start/end date and description.
1. Start services.
2. Both action Sync to AYON and auto-sync should be able to sync start/end date and description.

Sync: Sync start/end date and description

---

service_tools/requirements.txt
services/leecher/pyproject.toml
services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py
services/processor/pyproject.toml

First implementation of statuses sync for task and folder entities.
Because we don't sync statuses from ftrack to AYON we skip all status changes when the status is not available in AYON.
This PR requires ayon-python-api PR https://github.com/ynput/ayon-python-api/pull/188 so can't be tested right now.
1. Run services.
2. Sync a project, statuses from ftrack should be synced to AYON.
3. Change statuse on project with auto-sync, the change should be synced to AYON if status is available.

Sync: Folder and Task statuses

---

server/settings/publish_plugins.py

Settings for Standalone publisher have been removed as the tool is not present in Ayon. 
All should work as usual.

Remove Standalone publisher settings

---

services/processor/processor/lib/sync_from_ftrack.py

Use explicit kwargs for all arguments in `EntityHub`.
It is planned to change order of arguments in EntityHub ayon-python-api, this PR just makes sure nothing breaks when the update happens.
1. Nothing should change really.
2. Sync should work as did before.

Sync: Prepare for ayon api change

---

server/settings/service_handlers.py
services/processor/processor/default_handlers/action_prepare_project.py
services/processor/processor/default_handlers/action_sync_users.py
services/processor/processor/default_handlers/event_users_sync_from_ftrack.py
services/processor/processor/lib/__init__.py
services/processor/processor/lib/users.py

Added option to synchronize users and user roles from ftrack to AYON.
Users are synchronized based on email or username (email is used first class citizen). Admin is synchronized as admin, manager is synchronized as manager and any other user is synchronized as artist. Active states are synchronized too. Changes of private project are propagated to AYON access groups.
1. Start both services.
2. Run admin action `Sync users to AYON` on project.
3. Choose default access groups for new artists.
4. That should sync users from ftrack to AYON.
1. Create private project.
2. Run prepare project action.
3. The project in AYON should be available only for admins and managers.
5. In ftrack add permission to the project for some artist user.
6. The user in AYON should have permissions to see the …

Users: Sync users

---

client/ayon_ftrack/common/event_handlers/ftrack_base_handler.py
client/ayon_ftrack/common/ftrack_server.py
services/processor/processor/default_handlers/action_create_lists.py
services/processor/processor/handlers_to_convert/action_create_review_session.py
services/processor/processor/server.py

Event handlers have `cleanup` method which is called when ftrack server stops.
This works only for event handlers that were not discovered with `register` function in the file. This way we can call "cleanup" code related to handlers, for example threading timers.
Only way how to test it is to have running service for few days and validate that Create daily lists is executed only once each day.

Event handlers: Add cleanup method

---

service_tools/main.py

Fake submodule so class imported from it is considered as the same classes.
This is for cases when any base handle class is not imported from `ftrack_common` but from `ftrack_common.event_handlers`. In that case (if module is not in `sys.modules` yet), it will reimport the files again, which will cause different ids of classes. Preparing it for python will avoid importing it again.
1. When using service tools, it is possible to dicover action that imports base class from `ftrack_common.event_handlers`.

Service tools: Fake 'ftrack_common.event_handlers'

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py
services/processor/processor/lib/users.py

Sync ftrack to AYON can sync task assignees.
If users are synchronized it does allow to sync users from ftrack to AYON. During action are synchronized assignees from ftrack as are. If AYON user assigned on task cannot be mapped to ftrack user it is kept in AYON. Event processing just removed/adds assignee based on information from event.
_Only step 2 is required when using service tools._
1. If you're going to test PR using docker images, you have to first change version in `package.py` to e.g. `1.2.2-dev`.
2. Create addon package, upload it to server and use in bundle (+ copy settings).
3. Build docker leecher and process images.
4. Create services in AYON server.
5. Run ASH.
1. Make sure to run `AYON Admin - Sync users to AYON` first, so you have actually users to map.
2. Enabled auto …

To AYON Sync: Sync task assignees

---

service_tools/main.py

This is just enhancing faking `ftrack_common` in service tools.
Import each python file in `common` and map it to `ftrack_common` so any import from ftrack commond is valid when in service tools.
This is enhancement of issue connected to dicovering of event handlers.

Chore: Reimport whole 'common' as 'ftrack_common'

---

client/ayon_ftrack/common/__init__.py
client/ayon_ftrack/common/users.py
services/ayontof/ayontof/logic.py
services/processor/processor/default_handlers/action_prepare_project.py
services/processor/processor/default_handlers/action_sync_users.py
services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/default_handlers/event_users_sync_from_ftrack.py
services/processor/processor/lib/__init__.py
services/processor/processor/lib/sync_from_ftrack.py

Simple logic to sync assignees on task from AYON to ftrack.
1. Run `ayontof` service.
2. Make sure users on AYON server and ftrack are synchronized.
3. Change assignees on AYON.
4. The changes should be propagated to ftrack.
Resolves https://github.com/ynput/ayon-ftrack/issues/161

AYON to ftrack sync: Sync assignments on task

---

services/transmitter/transmitter/logic.py
services/transmitter/transmitter/service.py

Changes of attributes in AYON are propagated to ftrack.
Current implementation expects that attribute name matches custom attribute in ftrack. The value is not validated, so if types are not matching, or are invalid it will most probably fail (future enhancement).
1. Start transmitter service.
2. Change attributes in AYON.
3. All changed values should be propagated to ftrack.
Resolves https://github.com/ynput/ayon-ftrack/issues/162

AYON to ftrack sync: Sync attribute changes

---

services/processor/processor/ftrack_session.py

Processor service marks events stuck for 10 minutes as failed.
Avoid having stuck enrolled process jobs without option to "auto-fix". It is reasonable to say that event processing that takes more than 10 minutes should be processed other way than standard listener service. This auto-fix allows to use correct service name in enroll event function.
1. To find out if it works, one must have "stuck", with `"pending"` status, event with `ftrack.process` topic in events database.
2. If that happens then after 10 minutes is marked as failed so other processor services can continue.

Processor: Fail stuck process events

---

client/ayon_ftrack/event_handlers_user/action_download_reviews.py

Implemented simple action to download reviewable media from ftrack.
The action uses asset name and version for output filename, it does download the files to Downloads directory.
1. Create package, upload to server and use in bundle.
2. Start AYON launcher.
3. Run `Download Review Media` on Asset versions or Review sessions in ftrack.
4. It should download the reviewables to downloads directory.
Resolves https://github.com/ynput/ayon-ftrack/issues/132

Download review media action

---

client/ayon_ftrack/plugins/publish/collect_farm_env_variables.py

Fill environment variables for farm in publish plugins.
Move control to collect ftrack environment variables, needed for farm jobs, to ftrack addon.
1. At this moment probably nothing changed because deadline has to start using the key.
Resolves https://github.com/ynput/ayon-ftrack/issues/179

Fill environment variables for farm jobs

---

services/transmitter/Dockerfile
services/transmitter/manage.ps1

Copy ftrack common to docker image.
1. Built docker image contains `ftrack_common` so service can work.

Chore: Fix transmitter service manage script

---

services/leecher/leecher/listener.py
services/processor/processor/server.py
services/transmitter/transmitter/service.py

Don't set event summary in case of failed creation of ftrack session.
1. Set invalid server ftrack url in settings.
2. Run services.
3. They should crash and create event without any issues.

Services: Fix event summary

---

services/processor/processor/lib/sync_from_ftrack.py
services/transmitter/transmitter/logic.py

Do not try to fetch worklows if no workflow ids are collected.
Right now it would crash if there are not task type overrides in project schema.
1. Create project schema in ftrack without any task type overrides for tasks.
2. Create project with the schema.
3. Run all services.
4. Sync the project and do some status changes in AYON.
5. The changes should be propagated to ftrack.

Transmitter: Fix statuses fetching from ftrack

---

client/ayon_ftrack/plugins/publish/collect_webpublisher_credentials.py
server/settings/publish_plugins.py

Previous implementation was using regular (current) AYON account which failed for non admin accounts (`artist`, `freelancer`).
This uses wrapper for service account which is used to start ASH worker.
2. publish in WP

Wepublisher: use service account to query secrets

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py

Sync statuses and folder/task types on project sync.
Make sure that the project anatomy is matching ftrack scheme so statuses and entities sync work correctly.
1. Sync project from ftrack to AYON.
2. Statuses, folder types and task types from ftrack should be in AYON.
3. Change one project status in AYON to use different uppercase or lowercase (e.g. `On Hold` -> `on hold`).
4. Change some task in ftrack to the status (to `On Hold`).
5. Sync of the status should happen ok.
Resolves https://github.com/ynput/ayon-ftrack/issues/185

Sync folder/task types and statuses on project sync

---

server/settings/publish_plugins.py

Add `review` product type to maya product types. Added simple houdni, blender and 3ds max collection if instnces have review family.
1. Maya `review` product type is integrated to ftrack.
2. Instances with review family from houdini, blender and 3ds max are integrated to ftrack.
Resolves https://github.com/ynput/ayon-ftrack/issues/193

Collect ftrack family defaults

---

server/__init__.py
server/ftrack_session.py

Implemented base of simple async ftrack session to collect ftrack projects using server, api key and username from ftrack settings.
Implemented ftrack session is using `httpx` which is available on server. The list of ftrack projects is available under endpoint `/ftrackProjects`.
I don't know what error code I should return when it is not possible to create ftrack connection, e.g. because missing/invalid ftrack url or missing/invalid credentials. Right now it does return 200 with success and error information in response.
1. Create package, upload, use in bundle.
2. Fill ftrack url, service api key/username.
3. Call `GET` `{AYON server url}/addons/ftrack/1.3.3+dev/ftrackProjects` e.g. using `ayon_api`. If settings are set in dev or staging variant, then also add `?variant={variant}` to …

List ftrack project on AYON server

---

services/leecher/pyproject.toml
services/processor/pyproject.toml
services/transmitter/pyproject.toml

Define package mode in services pyproject.toml for newer peotry release.
1. It is possible to build service docker images.

Chore: Define package mode in services pyproject toml

---

client/ayon_ftrack/common/lib.py
client/ayon_ftrack/plugins/_unused_publish/integrate_ftrack_comments.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_description.py
client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Removed usage of `six` python module.
We don't support python 2 anymore so we can stop using `six`.
1. Everything should work as before.

Chore: Stop using 'six'

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py

Use `get_or_fetch_entity_by_id` instead of `get_or_query_entity_by_id`.
1. Services are doing their job with ayon-python-api >= 1.0.11 .

Chore: Avoid using deprecated function

---

services/transmitter/transmitter/logic.py

Version workflows are synchronized correctly.
Using correct key from workflow `status_id` instead of workflow's `id`.
1. Version workflows in ftrack don't cause issues with sync AYON to ftrack.

Transmitter: Use correct status field from workflow

---

client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Pass in missing argument to `get_all_attr_configs` in integrate hierarchy publish plugin.
1. Run editorial publishing, it should create entities or update attributes on entities.
2. It should work just fine.

Integrate hierarchy: Add missing argument

---

server/settings/desktopapp_handlers.py
server/settings/service_handlers.py

Renamed `SimpleAction` to `SimpleLocalAction` and `SimpleServiceAction` to make the class names unique.
Pydantic requires to have unique class names for scheme generation, luckily both models have currently same structure so it did not cause any issues.

Chore: Make settings model classes unique

---

services/processor/processor/lib/sync_from_ftrack.py

Reverse order of project statuses on sync to AYON.
The sort value used to sort statuses is not from first to last, but from last to first. Or rather, higher value goes first.
1. Start leecher and processor services.
2. Sync project.
3. Order of statuses in ftrack should match order of statuses in AYON.
Resolves https://github.com/ynput/ayon-tvpaint/issues/29

To AYON sync: Reverse order of project statuses on sync

---

pyproject.toml

Fix letters in pyproject.toml description.
AYON is meant to be used as `AYON` and ftrack is meant to be used as `ftrack`.

Chore: Lower ftrack and capitalize AYON in pyproject

---

client/ayon_ftrack/event_handlers_user/action_delivery.py

Updated code that runs delivery code.
The changes are implemented to met code in ayon-core's delivery load action and to avoid issues with using root from source representataion instead of using anatomy's roots.
1. Delivery actions works.
2. When running delivery on representation that was created e.g. on linux, it can be delivered on windows.
Resolves https://github.com/ynput/ayon-ftrack/issues/220

Delivery: Use code from ayon-core to run delivery
