ynput/ayon-ftrack

settings/desktopapp_handlers.py

Added missing settings models for desktop application handlers.
1. Add addon to server addons
2. Restart server
3. Open settings UI
4. It should not crash

Settings: Desktop app handlers settings

---

settings/main.py
settings/publish_plugins.py

Added settings for publish plugins.
1. Add addon to server addons
2. Restart server
3. Open settings UI
4. It should not crash

Settings: Publish plugin settings

---

client/ayon_ftrack/plugins/publish/collect_custom_attributes_data.py
client/ayon_ftrack/plugins/publish/collect_ftrack_api.py
client/ayon_ftrack/plugins/publish/collect_ftrack_family.py
client/ayon_ftrack/plugins/publish/collect_local_ftrack_creds.py
client/ayon_ftrack/plugins/publish/collect_username.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_component_overwrite.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_description.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_farm_status.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_note.py
client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py
client/ayon_ftrack/plugins/publish/validate_custom_ftrack_attributes.py

Fixed settings of publish plugins by adding 'settings_category' attribute.
This fix will start to take effect when current `develop` of OpenPype will be merged to `release/next-minor`.

Fix publish plugin settings

---

ftrack_common/event_handlers/ftrack_action_handler.py

Function `roles_check` makes sure the passed role names are lowered before checking them.

Safer case sensitivity of user roles

---

client/ayon_ftrack/plugins/publish/collect_ftrack_family.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_farm_status.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py
server/settings/publish_plugins.py
services/processor/processor/default_handlers/event_task_to_parent_status.py

Changed subset to product name and family to product type. Also fixed few misused settings values.

Products and settings fix

---

create_package.py
service_tools/start.ps1

Script `create_package.py` does create prepared zip file for server upload.
Script have options to create only folder structure or to create both using cli arguments if needed.

Create package does create server ready zip package

---

ftrack_common/constants.py
server/settings/main.py
service_tools/requirements.txt
services/leecher/leecher/listener.py
services/leecher/pyproject.toml
services/processor/processor/server.py
services/processor/pyproject.toml

Ftrack addon is using secrets for service username and api key and is using updated ayon api.

Settings with secrets

---

client/ayon_ftrack/launch_hooks/post_ftrack_changes.py

Use launch type in launch hook.

Application launch hook: Add launch type

---

client/ayon_ftrack/event_handlers_to_convert/action_delete_asset.py
client/ayon_ftrack/event_handlers_to_convert/action_delete_old_versions.py
client/ayon_ftrack/event_handlers_to_convert/action_delivery.py
client/ayon_ftrack/event_handlers_to_convert/action_djvview.py
client/ayon_ftrack/event_handlers_to_convert/action_fill_workfile_attr.py
client/ayon_ftrack/event_handlers_to_convert/action_prepare_project.py
client/ayon_ftrack/event_handlers_to_convert/action_rv.py
client/ayon_ftrack/event_handlers_to_convert/action_store_thumbnails_to_avalon.py
client/ayon_ftrack/event_handlers_user/action_applications.py
client/ayon_ftrack/event_handlers_user/action_batch_task_creation.py
client/ayon_ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
client/ayon_ftrack/event_handlers_user/action_client_review_sort.py
client/ayon_ftrack/event_handlers_user/action_component_open.py
client/ayon_ftrack/event_handlers_user/action_create_cust_attrs.py
client/ayon_ftrack/event_handlers_user/action_create_folders.py
client/ayon_ftrack/event_handlers_user/action_create_project_structure.py
client/ayon_ftrack/event_handlers_user/action_job_killer.py
client/ayon_ftrack/event_handlers_user/action_multiple_notes.py
client/ayon_ftrack/event_handlers_user/action_test.py
client/ayon_ftrack/event_handlers_user/action_thumbnail_to_childern.py
client/ayon_ftrack/event_handlers_user/action_thumbnail_to_parent.py
client/ayon_ftrack/event_handlers_user/action_where_run_ask.py

Use `LocalAction` base for local actions.

Fix actions inheritance

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py
server/__init__.py

Add `ftrackId` attribute to version scope. The change requires to fix older versions of ftrack addon. Modified the attribute checks to only check for required scopes instead of checking for explicit scopes.

Add ftrack id attribute to version

---

client/ayon_ftrack/scripts/sub_user_server.py

Safer handling of user ftrack event server. This is to avoid error message on startup, if anything goes wrong.

User ftrack server is safer

---

ftrack_common/custom_attributes.json
server/settings/custom_attributes.py
server/settings/main.py

Added missing custom attributes settings.

Settings: Add missing custom attributes

---

services/leecher/Dockerfile
services/leecher/Makefile
services/leecher/leecher/listener.py
services/leecher/manage.ps1
services/leecher/pyproject.toml
services/processor/Dockerfile
services/processor/Makefile
services/processor/manage.ps1
services/processor/processor/server.py
services/processor/pyproject.toml

Fixed services to make correct docker images. Make explicit copy of files that should be in images. Use correct settings getter in services. Bumped ayon-python-api.

Docker service build fix

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py

Fix import from common in integrate ftrack api.

Fix import in integrate ftrack api

---

services/processor/processor/server.py

Use service settings instead of production settings.

Processor service: Use correct settings

---

service_tools/requirements.txt
services/leecher/leecher/listener.py
services/processor/processor/server.py

Services do not crash if ftrack credentials in settings are invalid, instead just log and create log event on server. Service sleeps for 10 seconds if service can't connect to AYON server.

Better services logging

---

service_tools/start.ps1
services/leecher/manage.ps1
services/processor/manage.ps1

Use 'script_dir' instead of 'current_dir' which is current work directory. Fix or condition in service tools script.

Windows scripts: Fix used dir

---

client/ayon_ftrack/plugins/publish/collect_webpublisher_credentials.py
server/settings/publish_plugins.py

Cleanup code in webpublisher plugin.

Webpublisher code cleanup

---

server/settings/publish_plugins.py

Added missing settings for advanced filtering in `CollecFtrackFamily` plugin.

Collect Ftrack Family: Add missing advanced filtering setting

---

create_package.py

Create package script can extract only client code to predefined directory. That can be handy for development.

Create package can create only client

---

services/processor/processor/server.py

Fix variable usage in processor.

Fix variable usage

---

client/ayon_ftrack/plugins/publish/collect_ftrack_api.py
client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Prepare ftrack addon to be able to handle cases when folder path is used as unique identifier in publishing.
Related to this PR https://github.com/ynput/OpenPype/pull/5817 . This PR is not dependent on it and can be merged earlier.

Use folder paths as unique identifier

---

client/ayon_ftrack/event_handlers_to_convert/action_delivery.py
client/ayon_ftrack/event_handlers_to_convert/action_prepare_project.py
client/ayon_ftrack/event_handlers_user/action_create_project_structure.py
server/settings/desktopapp_handlers.py

Removed usage of "Pypeclub" role in event handlers and their settings.

Removed Pypeclub role

---

services/leecher/pyproject.toml
services/processor/processor/ftrack_session.py
services/processor/pyproject.toml

Fix indentation in processor and update ayon python api to fix some issues with events enrolling.

Fix ftrack session enroll event

---

server/settings/main.py

Change position of service user settings in UI to be after server url.

Settings: Move service settings

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py

Make sure variable `task_name` is defined.

Integrate ftrack api: Fix issue with undefined variable

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py

Fix missing 'path' attribute on 'TaskEntity'.

Sync event handler log fix

---

service_tools/requirements.txt

Update ayon-python-api in service tools.

Service tools: Update ayon api

---

README.md

Added basic development and testing instructions.

Readme: Added development and testing instructions

---

client/ayon_ftrack/event_handlers_user/action_create_folders.py

Add missing `"folder"` key to template data.

Create folders action fix

---

server/settings/desktopapp_handlers.py

Removed unused settings `application_launch_statuses`.

Settings cleanup: Removed unused status change settings

---

services/processor/processor/default_handlers/action_prepare_project.py

Validate project name and code before running prepare project action and give option to change them. And add validation of unique project code.
Before this PR the action just crashes without any detailed information.
There was discovered that we actually do not validate if project code is unique. We probably should add action which would allow to change project name and code, because those changes can be done only via API and cannot be done in ftrack WebUI.
Why is project code important validation? You can have existing AYON project with different name but same code. In that case we cannot sync it.
1. Run services using service tools
2. Create ftrack project with invalid name and code e.g. `"Můj krásný projekt"` and `"MůKP"`.
3. Run prepare project on the project.
4. It should tell you …

Enhancement: Prepare action gives option to change ftrack name and code

---

client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Integration of hierarchy works again in ftrack addon. It was broken because of using folder path during publishing.

Integrate hierarchy works with folder paths

---

server/settings/service_handlers.py

Commented out `create_daily_review_session` settings which are for action which si not yet converted for AYON, and it's conversion requires resolving few issues connected with its logic.

Removed unused settings for daily review session

---

client/ayon_ftrack/tray/user_server.py
services/processor/processor/ftrack_session.py

Removed environment variables that are OpenPype related or they're not changing.

Remove unused env variables

---

client/ayon_ftrack/resources/__init__.py
client/ayon_ftrack/resources/sign_in_message.html
client/ayon_ftrack/tray/login_dialog.py
client/ayon_ftrack/tray/login_tools.py

Up this point was the sign in message file supplied by openpype addon.
1. Create package and upload to server.
2. Launch tray.
3. Logout in ftrack addon login. (skip if not logged in).
4. Open ftrack addon login dialog and press `Login`.
5. Browser should show up and after login should be shown page "You can close this window now".

Moved sign in message html to addon

---

client/ayon_ftrack/event_handlers_user/action_create_folders.py

Refactored hierarchy queries to avoid possible issues with querying empty set of ids.

Refactor create folders queries

---

client/ayon_ftrack/launch_hooks/post_ftrack_changes.py

Fix value conversion from settings as value is not string but list of strings.
1. Status change should work on application launch

Post launch status change fix

---

services/processor/processor/default_handlers/action_create_lists.py
services/processor/processor/handlers_to_convert/action_create_review_session.py

Stop chrono callbacks if the session they're listening too is closed.

Service: Stop chrono callback if session is closed

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py
server/settings/publish_plugins.py

Remove option to add OpenPype version and added option to add ftrack addon version and launcher version to integrated metadata.

Added launcher and ftrack addon version to integrate metadata

---

server/settings/common.py
server/settings/custom_attributes.py
server/settings/desktopapp_handlers.py
server/settings/main.py
server/settings/publish_plugins.py
server/settings/service_handlers.py

Use `SettingsField` over `Field` in settings model.

Settings: Use 'SettingsField' over 'Field'

---

package.py

Added compatibility information to package.py

Chore: Add compatibility info

---

services/processor/processor/default_handlers/action_prepare_project.py

List values are validated against available values on custom attribute.
1. Make sure applications custom attribute on ftrack does not have an application that is available in AYON.
2. Create project in ftrack.
3. Run prepare project on the project.
4. Make sure the application from 1. is checked and submit preparation.
5. It should not crash.

Prepare project: Validate list values on set attributes

---

client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py

Publishing a review (or uploading) when the hierachy was not already created, would result in the Ftrack component not being created.

Fix hierarchy integration from NukeStudio/Hiero.

---

server/settings/service_handlers.py
services/processor/processor/default_handlers/action_project_component_sizes.py

Added action for calculation of components size on ftrack per project.
1. Create ftrack package
2. Upload the package on server
3. Add it to bundle (you can use dev bundle)
4. Run service tools `./service_tools/start.ps1 services` (can be added `--variant <dev bundle name>`)
5. Action should not show if your role does not have correct permissions based on settings, or if the action is disabled
6. You can run the action almost anywhere
7. Select a project or choose "all projects" option
8. It should start to calculate them

Service Action: Project component size action

---

client/ayon_ftrack/ftrack_addon.py

Remove unnecessary cli handling from client addon. That also fixes issue with missing `click`.

Chore: Remove unused click

---

client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py

Fix wrong paths of integrated components.

Integration: Use correct representation path

---

client/ayon_ftrack/event_handlers_user/action_create_folders.py
client/ayon_ftrack/event_handlers_user/action_create_project_structure.py

Tell user that project is not found in AYON to be able to run action.

Actions: Report that there is missing project in AYON for the action

---

server/settings/main.py

Defaul values of custom attributes were not used as default values.

Default values of custom attributes roles

---

client/ayon_ftrack/ftrack_addon.py

Added `version` attribute to client addon class.

Chore: Add version to client addon

---

client/ayon_ftrack/common/custom_attributes.json
client/ayon_ftrack/event_handlers_user/action_create_cust_attrs.py

Added more decimal places to fps custom attribute.

Custom attributes: FPS has precision 6

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/lib/sync_from_ftrack.py

Make mapping of `tools_env` to `tools` attribute during sync.

Sync: Fix tools sync

---

client/ayon_ftrack/launch_hooks/post_ftrack_changes.py

Launch of application should correctly set next ftrack status on task.

PostLaunch hook: Fix next status on launch

---

client/ayon_ftrack/common/event_handlers/ftrack_action_handler.py
client/ayon_ftrack/event_handlers_user/action_applications.py
client/ayon_ftrack/ftrack_addon.py
client/ayon_ftrack/launch_hooks/post_ftrack_changes.py
client/ayon_ftrack/plugins/publish/integrate_ftrack_status.py
client/ayon_ftrack/tray/user_server.py
services/processor/processor/default_handlers/action_prepare_project.py
services/processor/processor/default_handlers/event_first_version_status.py
services/processor/processor/default_handlers/event_sync_from_ftrack.py
services/processor/processor/handlers_to_convert/event_sync_to_avalon.py

Cleaned up code for ruff linter.
Removed unused imports and variables, added missing imports, fixed some formatting issues.

Chore: Cleanup code for ruff

---

client/ayon_ftrack/version.py
create_package.py

Update create package script from latest addon template repository.
1. Create package using `python ./create_package.py` inside repository.
2. Created package should be exactly the same as before this PR, but faster.

Chore: Updated create package script

---

ruff.toml
service_tools/main.py
services/leecher/leecher/listener.py

Cleaned up code for ruff linter.
Removed unused imports and variables, added missing imports, fixed some formatting issues.

Chore: Cleanup code for ruff n2

---

create_package.py

Create package also updates version in services.
1. Change version in `package.py`.
2. Run `python ./create_package.py`.
3. If you check changes you should see that also version of services did change.

Create package: Update services versions

---

service_tools/main.py
services/leecher/leecher/listener.py
services/processor/processor/server.py

Service logs now print timestamp.
1. Run services.
2. Their logs should also print timestamp.

Services: Add timestamps to service logs

---

client/ayon_ftrack/common/ftrack_server.py
services/processor/processor/download_utils.py
services/processor/processor/ftrack_session.py
services/processor/processor/server.py

Try to implement better cleanup of processor.
This occurs error with stuck ftrack event processor, the reason is not fully unknown, so this is another possible fix PR.

Fix: Ftrack processor cleanup (attempt 2)

---

.github/workflows/release_trigger.yml

Added release trigger CI action to repository.

Chore: Add release trigger ci action

---

.github/workflows/deploy_docker_images.yml
services/leecher/Makefile
services/processor/Makefile

Trigger docker image build and push on release.
This is more draft than a ready to test PR. I'm not sure if I did it correctly yet.

Chore: Action to push docker images

---

services/processor/processor/default_handlers/action_sync_users.py

Use correct attribute to fill full name. Skip service and demo users. Fixed issues with user roles.
1. Run sync users action.
2. Full name should be filled.

Users sync: Fix multiple issues with sync

---

client/ayon_ftrack/event_handlers_user/action_applications.py

Use 'get_applications_for_context' from 'applications' addon to get available applications.
The action was still based on applications attribute instead of settings based logic.
1. Make sure applications attribute in AYON is empty (or not existing).
2. Discover actions on task in ftrack.
3. You should see same set of applications as in launcher tool.

Applications action: Don't rely on applications attribute

---

services/transmitter/transmitter/logic.py
services/transmitter/transmitter/service.py

Added sync of statuses from AYON to ftrack.
Change of status on folder, task or version is propagated to ftrack (if the status is available for the entity in ftrack).
1. Start transmitter service.
2. Make sure to have project in both ftrack and AYON.
3. Make sure ftrack is enabled on project (in ftrack settings).
4. Change status in AYON.
5. The status if ftrack should be changed too.
Resolves https://github.com/ynput/ayon-ftrack/issues/160

AYON to ftrack sync: Sync statuses

---

services/processor/processor/lib/sync_from_ftrack.py

Sync project statuses during prepare project action.
We're now synchronizing statuses on Prepare project action in AYON.
1. Run Prepare project on a ftack project (it must not exist in AYON).
2. After sync, the project should have available the same statuses as ftrack does.

Prepare project: Sync project statuses on project creation

---

server/__init__.py
server/ftrack_import.py

Added endpoint to import ftrack users into AYON.

Endpoint to import ftrack users

---

README.md

Readme: Updated services information

---

services/transmitter/transmitter/logic.py

AYON project attributes are synchronized to ftrack.
AYON does not trigger `entity.project.attrib_changed` so we have to use `entity.project.changed`.
1. Start services, e.g. using service tools.
2. Change attribute on project in AYON.
3. The attribute value should be synced to ftrack.

Transmitter: Sync project attributes to ftrack

---

services/processor/processor/default_handlers/action_prepare_project.py

Selected value of auto sync during Prepare project action is actually propagated to custom attributes.
1. Enable attributes mapping `ayon+settings://ftrack/custom_attributes/attributes_mapping`
2. Run services with changes from this PR.
3. Run Prepare Project action on a project.
4. Select `Auto sync`.
5. Confirm > Confirm > Wait until preparation finished.
6. Select the project in ftrack and `Auto sync` in custom attributes should be enabled.
Resolves https://github.com/ynput/ayon-ftrack/issues/206

Chore: Prepare project does set auto sync based on selected value

---

services/processor/processor/default_handlers/event_sync_from_ftrack.py

Clear AYON id value from copy->pasted tasks and folders.
1. Start services.
2. Enabled auto-sync on a project.
3. Copy->paste tasks in the project.
4. "New tasks" should be synchronized to AYON and should have different AYON id in ftrack.
Resolves https://github.com/ynput/ayon-ftrack/issues/200

clear ayon ids from new entities if are duplicated
